### ISSUE TITLE
Feature Request: Support Watchkit icons

### ISSUE THREAD

**Issue by viezel** [FokkeZB/TiCons#19]
Could be cool to add watchkit icons. Either generated from the app icon, or using its own upload field. 

ref: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/WatchHumanInterfaceGuidelines/IconandImageSizes.html

<table class="graybox" border="0" cellspacing="0" cellpadding="5"><caption class="tablecaption"></caption><thead><tr><th scope="col" class="TableHeading_TableRow_TableCell">
Asset 

</th><th scope="col" class="TableHeading_TableRow_TableCell">
Apple Watch (38mm) 

</th><th scope="col" class="TableHeading_TableRow_TableCell">
Apple Watch (42mm) 

</th></tr></thead><tbody><tr><td scope="row">
Notification Center icon 

</td><td>
48 pixels 

</td><td>
55 pixels 

</td></tr><tr><td scope="row">
Long-Look notification icon 

</td><td>
80 pixels 

</td><td>
88 pixels 

</td></tr><tr><td scope="row">
Home Screen icon 

</td><td>
80 pixels 

</td><td>
80 pixels 

</td></tr><tr><td scope="row">
Short-Look icon 

</td><td>
172 pixels 

</td><td>
196 pixels 

</td></tr></tbody></table>

**Comment by FokkeZB** [comment]
I assume the border radius is to be added by Apple? Any idea of what files names they should have?

**Comment by viezel** [comment]
44x44@2x.png (Homescreen 42mm)
86x86@2x.png (Short Look 38mm)
29x29@2x.png (Companion Settings)
24x24@2x.png (Notification Center 38mm)
98x98@2x.png (Short Look 42mm)
29x29@3x.png (Companion Settings)
27.5x27.5@2x.png (Notification Center 42mm)

**Comment by viezel** [comment]
but apple is kind of wage on that.. Im not sure how appc will implement it.

**Comment by viezel** [comment]
yeah the border radius is apples work.. so just square images

**Comment by dsshap** [comment]
+1 on this feature

**Comment by FokkeZB** [comment]
I just added this to the CLI. I might try to do a NodeJS versions of the web version today so I don't have to maintain a PHP version no longer.

**Comment by FokkeZB** [comment]
Closing since this PHP version will be replaced by a NodeJS version using the CLI which already has this taken care of.
