### ISSUE TITLE
Can you add API ?

### ISSUE THREAD

**Issue by abada** [FokkeZB/TiCons#20]
Hi ,

Thanks fokke to make appc developer`s life better :)

Can you please add api for ticons service ?

I want my client create icons and splashes from my admin  ?

Thanks

**Comment by FokkeZB** [comment]
I'd suggest you use the TiCons CLI (https://www.npmjs.com/package/ticons) for that on your server.

I working on migrating the web-service to NodeJS and might add an API there.

**Comment by abada** [comment]
Thanks :)
