### ISSUE TITLE
Error: Unable to set image alpha channel

### ISSUE THREAD

**Issue by FokkeZB** [FokkeZB/TiCons#22]
By Vivian:

Problem is with the default (non-transparant) icon.
I think I’ve figured it out. It seems that the Android and iOS icons are swapped?
iOS - I’m able to upload a transparent icon
Android - After export it puts a white background to make it non transparent.

![apple](https://cloud.githubusercontent.com/assets/2699409/8020564/d04333ca-0c7d-11e5-8820-13ef7e4709ff.png)

**Comment by FokkeZB** [comment]
Also by William:

I forgot to mention that for png from AI and photoshop all work fine. But a quick test initially on arriving on the site a couple of days back with png created on MS paint fails with the stated error.

![1024](https://cloud.githubusercontent.com/assets/2699409/8020616/3d300be2-0c7f-11e5-8374-2b2e5800b3fa.png)

**Comment by findvivian** [comment]
Thanks for taking a look into this! :)

**Comment by FokkeZB** [comment]
Some PHP update made removing the alpha channel not to work anymore. I've removed that line, but it might well be that the generated images are no longer acceptable for Apple and Google if the source file contains an alpha channel. Better use the CLI :)

**Comment by findvivian** [comment]
Thank you for fixing the generator! This helps me out a ton, you can't even imagine :)
Not sure what a CLI is..seems complicated already :( 

Thanks again!
